---
- hosts: all
  vars_files:
    - variables.yml
  vars:
     # The `ansible_ssh` vars are needed for establishing the initial password-based connection
     ansible_ssh_pass: raspberry
     ansible_ssh_common_args: "-o PreferredAuthentications=password -o StrictHostKeyChecking=no"
 
  gather_facts: no
  become: yes

  tasks:
    - name: Validate Configuration
      assert: 
        that: ssh_github_user is defined or ssh_public_key_files is defined

    - name: Deploy a local SSH Key 
      authorized_key:
        user: "{{ ansible_user }}"
        key: "{{ lookup('file', item) }}"
        state: present
      with_items: "{{ ssh_public_key_files }} "
      when: ssh_public_key_files is defined

    - name: Deploy SSH Keys from GitHub
      authorized_key:
        user: "{{ ansible_user }}"
        key: "https://github.com/{{ ssh_github_user }}.keys"
        state: present
      when: ssh_github_user is defined

    - name: Disable Password Authentication
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "^PasswordAuthentication"
        line: "PasswordAuthentication no"
        state: present
      notify:
        - restart ssh

  handlers:
    - name: restart ssh
      service:
        name: sshd
        state: restarted

