---
- hosts: servers_ssh_key
  vars:
    target_timezone: Europe/Sofia
    apt_packages:
    - vim
    - cec-utils
    config_targets:
    - { name: hostname, target: raspi3, reboot: True }
    - { name: boot_splash, target: 1, ignore_errors: True }
    - { name: camera, target: 0 }
    - { name: wifi_country, target: BG, ignore_errors: True }
 
  gather_facts: no
  become: yes

  pre_tasks:
    - name: Install packages
      apt:
        pkg: "{{ apt_packages }}"
        state: present

    - name: Configure
      include_role:
        name: raspi_config
      with_items: "{{ config_targets }}"

#  roles:
#  - role: raspi_config_timezone
#    vars:
#      target: "{{ target_timezone }}"
#  - disable_power_led
#  - kodi
#  - raspi_config_expandfs

