---
- name: Read current timezone
  slurp:
    src: /etc/timezone
  register: current_timezone

- debug:
    var: current_timezone.content | b64decode

- name: Set timezone to `{{ raspi_config_target_timezone }}`
  command:
    cmd: "raspi-config nonint do_change_timezone {{ raspi_config_target_timezone }}"
  when: current_timezone.content | b64decode | trim != raspi_config_target_timezone | string
