---
- name: Validate Configuration
  assert:
    that: ssh_github_user is defined or ssh_public_key_files is defined

- name: Deploy local SSH Keys
  authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ lookup('file', item) }}"
    state: present
  with_items: "{{ ssh_public_key_files }} "
  when: ssh_public_key_files is defined

- name: Deploy SSH Keys from GitHub
  authorized_key:
    user: "{{ ansible_user }}"
    key: "https://github.com/{{ ssh_github_user }}.keys"
    state: present
  when: ssh_github_user is defined
